import 'dart:io';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:share_plus/share_plus.dart';
import '../app_theme.dart';
import '../models/user_profile.dart';
import '../models/health_profile.dart';
import '../models/emergency_contact.dart';
import '../services/profile_service.dart';
import '../services/health_service.dart';
import '../services/contact_service.dart';
import '../widgets/reusable_widgets.dart';

class IceCardScreen extends StatefulWidget {
  const IceCardScreen({super.key});

  @override
  State<IceCardScreen> createState() => _IceCardScreenState();
}

class _IceCardScreenState extends State<IceCardScreen>
    with SingleTickerProviderStateMixin {
  late AnimationController _fadeController;
  late Animation<double> _fadeAnimation;

  UserProfile _profile = UserProfile();
  HealthProfile _health = HealthProfile();
  List<EmergencyContact> _contacts = [];
  bool _isLoading = true;
  String _emergencyId = '';

  @override
  void initState() {
    super.initState();
    _fadeController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 800),
    );
    _fadeAnimation = CurvedAnimation(
      parent: _fadeController,
      curve: Curves.easeOutCubic,
    );
    _loadData();
  }

  @override
  void dispose() {
    _fadeController.dispose();
    super.dispose();
  }

  Future<void> _loadData() async {
    final profile = await ProfileService.getProfile();
    final health = await HealthService.getProfile();
    final contacts = await ContactService.getContactsByPriority();
    setState(() {
      _profile = profile;
      _health = health;
      _contacts = contacts;
      _emergencyId = 'SOS-${profile.fullName.hashCode.abs().toString().padLeft(8, '0')}';
      _isLoading = false;
    });
    _fadeController.forward();
  }

  String _buildQRData() {
    final data = {
      'type': 'ICE',
      'name': _profile.fullName,
      'blood': _profile.bloodGroup ?? '',
      'allergies': _health.allergies,
      'conditions': _health.existingDiseases,
      'medications': _health.currentMedications,
      'donor': _health.organDonorStatus,
      'contacts': _contacts.take(3).map((c) => {
            'name': c.name,
            'phone': c.phone,
            'relation': c.relationship,
          }).toList(),
    };
    return json.encode(data);
  }

  Future<void> _shareICECard() async {
    final buffer = StringBuffer();
    buffer.writeln('🆘 IN CASE OF EMERGENCY (ICE)');
    buffer.writeln('═══════════════════════════');
    buffer.writeln();
    buffer.writeln('Name: ${_profile.fullName}');
    if (_profile.bloodGroup != null) {
      buffer.writeln('Blood Group: ${_profile.bloodGroup}');
    }
    if (_profile.age != null) buffer.writeln('Age: ${_profile.age}');
    buffer.writeln();
    if (_health.allergies.isNotEmpty) {
      buffer.writeln('⚠️ Allergies: ${_health.allergies.join(", ")}');
    }
    if (_health.existingDiseases.isNotEmpty) {
      buffer.writeln('🏥 Conditions: ${_health.existingDiseases.join(", ")}');
    }
    if (_health.currentMedications.isNotEmpty) {
      buffer.writeln('💊 Medications: ${_health.currentMedications.join(", ")}');
    }
    if (_health.organDonorStatus) {
      buffer.writeln('♥️ Organ Donor: Yes');
    }
    buffer.writeln();
    buffer.writeln('📞 Emergency Contacts:');
    for (final c in _contacts.take(3)) {
      buffer.writeln('  • ${c.name} (${c.relationship}): ${c.phone}');
    }
    buffer.writeln();
    buffer.writeln('ID: $_emergencyId');
    buffer.writeln('Generated by AI Smart SOS');

    await Share.share(buffer.toString());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: const BoxDecoration(gradient: AppTheme.backgroundGradient),
        child: ParticleBackground(
          seed: 101,
          child: SafeArea(
            child: _isLoading
                ? const Center(
                    child: CircularProgressIndicator(color: AppTheme.primaryCyan))
                : FadeTransition(
                    opacity: _fadeAnimation,
                    child: Column(
                      children: [
                        _buildHeader(),
                        Expanded(
                          child: SingleChildScrollView(
                            physics: const BouncingScrollPhysics(),
                            padding: const EdgeInsets.symmetric(
                                horizontal: 20, vertical: 8),
                            child: Column(
                              children: [
                                _buildICECard(),
                                const SizedBox(height: 16),
                                _buildContactsSection(),
                                const SizedBox(height: 16),
                                _buildQRSection(),
                                const SizedBox(height: 24),
                                _buildShareButton(),
                                const SizedBox(height: 32),
                              ],
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
          ),
        ),
      ),
    );
  }

  Widget _buildHeader() {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
      child: Row(
        children: [
          GestureDetector(
            onTap: () => Navigator.pop(context),
            child: Container(
              width: 40, height: 40,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                color: AppTheme.glassWhite,
                border: Border.all(color: AppTheme.glassBorder),
              ),
              child: const Icon(Icons.arrow_back_ios_new,
                  color: AppTheme.textPrimary, size: 18),
            ),
          ),
          const SizedBox(width: 12),
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('ICE CARD',
                  style: AppTheme.headingSmall.copyWith(fontSize: 14)),
              Text('In Case of Emergency',
                  style: AppTheme.bodySmall.copyWith(fontSize: 11)),
            ],
          ),
          const Spacer(),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
            decoration: BoxDecoration(
              color: AppTheme.emergencyRed.withValues(alpha: 0.1),
              borderRadius: BorderRadius.circular(10),
              border: Border.all(
                  color: AppTheme.emergencyRed.withValues(alpha: 0.3)),
            ),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(Icons.sos, color: AppTheme.emergencyRed, size: 16),
                const SizedBox(width: 4),
                Text('ICE',
                    style: AppTheme.bodySmall.copyWith(
                      color: AppTheme.emergencyRed,
                      fontWeight: FontWeight.w700,
                      fontSize: 12,
                    )),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildICECard() {
    final hasPhoto = _profile.profilePhotoPath != null &&
        File(_profile.profilePhotoPath!).existsSync();

    return Container(
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(24),
        gradient: const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            Color(0xFF1A1A2E),
            Color(0xFF16213E),
            Color(0xFF0F3460),
          ],
        ),
        border: Border.all(
          color: AppTheme.emergencyRed.withValues(alpha: 0.3),
          width: 2,
        ),
        boxShadow: [
          BoxShadow(
            color: AppTheme.emergencyRed.withValues(alpha: 0.15),
            blurRadius: 30,
            spreadRadius: 5,
          ),
        ],
      ),
      child: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          children: [
            // Top bar: ICE label + emergency ID
            Row(
              children: [
                Container(
                  padding:
                      const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                  decoration: BoxDecoration(
                    color: AppTheme.emergencyRed,
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: const Text('ICE',
                      style: TextStyle(
                        color: Colors.white,
                        fontWeight: FontWeight.w900,
                        fontSize: 14,
                        letterSpacing: 3,
                      )),
                ),
                const Spacer(),
                Text(_emergencyId,
                    style: AppTheme.bodySmall.copyWith(
                      color: AppTheme.textMuted,
                      fontFamily: 'monospace',
                      fontSize: 11,
                    )),
              ],
            ),
            const SizedBox(height: 20),

            // Profile photo + Name + Blood group
            Row(
              children: [
                Container(
                  width: 72,
                  height: 72,
                  decoration: BoxDecoration(
                    shape: BoxShape.circle,
                    border: Border.all(color: AppTheme.primaryCyan, width: 2.5),
                    image: hasPhoto
                        ? DecorationImage(
                            image: FileImage(File(_profile.profilePhotoPath!)),
                            fit: BoxFit.cover,
                          )
                        : null,
                    gradient: hasPhoto ? null : AppTheme.cyanGradient,
                  ),
                  child: hasPhoto
                      ? null
                      : Center(
                          child: Text(
                            _profile.fullName.isNotEmpty
                                ? _profile.fullName[0].toUpperCase()
                                : '?',
                            style: AppTheme.headingSmall.copyWith(
                              color: Colors.white,
                              fontSize: 28,
                            ),
                          ),
                        ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        _profile.fullName.isNotEmpty
                            ? _profile.fullName
                            : 'Name Not Set',
                        style: AppTheme.headingSmall.copyWith(fontSize: 20),
                      ),
                      if (_profile.age != null)
                        Text('Age: ${_profile.age}',
                            style: AppTheme.bodySmall
                                .copyWith(color: AppTheme.textSecondary)),
                      if (_profile.gender != null)
                        Text(_profile.gender!,
                            style: AppTheme.bodySmall.copyWith(fontSize: 12)),
                    ],
                  ),
                ),
                if (_profile.bloodGroup != null)
                  Container(
                    width: 52,
                    height: 52,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(14),
                      color: AppTheme.emergencyRed.withValues(alpha: 0.15),
                      border: Border.all(
                        color: AppTheme.emergencyRed.withValues(alpha: 0.5),
                        width: 2,
                      ),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      _profile.bloodGroup!,
                      style: AppTheme.headingSmall.copyWith(
                        color: AppTheme.emergencyRed,
                        fontSize: 18,
                      ),
                    ),
                  ),
              ],
            ),
            const SizedBox(height: 20),

            // Divider
            Container(
              height: 1,
              color: AppTheme.glassWhite.withValues(alpha: 0.4),
            ),
            const SizedBox(height: 16),

            // Medical Info Row
            if (_health.allergies.isNotEmpty ||
                _health.existingDiseases.isNotEmpty ||
                _health.currentMedications.isNotEmpty) ...[
              if (_health.allergies.isNotEmpty)
                _buildInfoRow(Icons.warning_amber_rounded, 'Allergies',
                    _health.allergies.join(', '), AppTheme.emergencyRed),
              if (_health.existingDiseases.isNotEmpty)
                _buildInfoRow(Icons.medical_services_outlined, 'Conditions',
                    _health.existingDiseases.join(', '), AppTheme.warningAmber),
              if (_health.currentMedications.isNotEmpty)
                _buildInfoRow(Icons.medication_outlined, 'Medications',
                    _health.currentMedications.join(', '), const Color(0xFF448AFF)),
              const SizedBox(height: 8),
            ],

            // Organ Donor badge
            if (_health.organDonorStatus)
              Container(
                width: double.infinity,
                padding:
                    const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
                decoration: BoxDecoration(
                  color: AppTheme.successGreen.withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(10),
                  border: Border.all(
                      color: AppTheme.successGreen.withValues(alpha: 0.3)),
                ),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(Icons.volunteer_activism,
                        color: AppTheme.successGreen, size: 18),
                    const SizedBox(width: 8),
                    Text('REGISTERED ORGAN DONOR',
                        style: AppTheme.bodySmall.copyWith(
                          color: AppTheme.successGreen,
                          fontWeight: FontWeight.w700,
                          letterSpacing: 1.5,
                          fontSize: 11,
                        )),
                  ],
                ),
              ),
          ],
        ),
      ),
    );
  }

  Widget _buildInfoRow(
      IconData icon, String label, String value, Color color) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 10),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(icon, color: color, size: 18),
          const SizedBox(width: 10),
          Text('$label: ',
              style: AppTheme.bodySmall.copyWith(
                color: color,
                fontWeight: FontWeight.w600,
                fontSize: 12,
              )),
          Expanded(
            child: Text(value,
                style: AppTheme.bodySmall.copyWith(
                  color: AppTheme.textSecondary,
                  fontSize: 12,
                )),
          ),
        ],
      ),
    );
  }

  Widget _buildContactsSection() {
    if (_contacts.isEmpty) {
      return GlassCard(
        borderColor: AppTheme.warningAmber.withValues(alpha: 0.2),
        child: Row(
          children: [
            Icon(Icons.warning_amber,
                color: AppTheme.warningAmber, size: 24),
            const SizedBox(width: 12),
            Expanded(
              child: Text('No emergency contacts added yet',
                  style: AppTheme.bodyMedium.copyWith(
                    color: AppTheme.warningAmber,
                  )),
            ),
          ],
        ),
      );
    }

    return Column(
      children: _contacts.take(3).map((contact) {
        return Container(
          margin: const EdgeInsets.only(bottom: 10),
          child: GlassCard(
            padding: const EdgeInsets.all(16),
            borderColor: AppTheme.primaryCyan.withValues(alpha: 0.15),
            child: Row(
              children: [
                Container(
                  width: 44, height: 44,
                  decoration: BoxDecoration(
                    shape: BoxShape.circle,
                    color: AppTheme.primaryCyan.withValues(alpha: 0.12),
                  ),
                  child: Center(
                    child: Text(
                      contact.name.isNotEmpty ? contact.name[0].toUpperCase() : '?',
                      style: AppTheme.headingSmall.copyWith(
                        color: AppTheme.primaryCyan,
                        fontSize: 18,
                      ),
                    ),
                  ),
                ),
                const SizedBox(width: 14),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(contact.name,
                          style: AppTheme.bodyMedium.copyWith(
                            color: AppTheme.textPrimary,
                            fontWeight: FontWeight.w600,
                          )),
                      Text('${contact.relationship} • ${contact.phone}',
                          style: AppTheme.bodySmall.copyWith(fontSize: 12)),
                    ],
                  ),
                ),
                if (contact.priority == ContactPriority.primary)
                  Container(
                    padding: const EdgeInsets.symmetric(
                        horizontal: 8, vertical: 4),
                    decoration: BoxDecoration(
                      color: AppTheme.warningAmber.withValues(alpha: 0.1),
                      borderRadius: BorderRadius.circular(6),
                    ),
                    child: Text('⭐',
                        style: AppTheme.bodySmall.copyWith(fontSize: 12)),
                  ),
              ],
            ),
          ),
        );
      }).toList(),
    );
  }

  Widget _buildQRSection() {
    return GlassCard(
      borderColor: AppTheme.primaryCyan.withValues(alpha: 0.2),
      child: Column(
        children: [
          Row(
            children: [
              Icon(Icons.qr_code, color: AppTheme.primaryCyan, size: 20),
              const SizedBox(width: 8),
              Text('EMERGENCY QR CODE',
                  style: AppTheme.bodySmall.copyWith(
                    letterSpacing: 2,
                    fontWeight: FontWeight.w600,
                    color: AppTheme.primaryCyan,
                  )),
            ],
          ),
          const SizedBox(height: 16),
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(16),
            ),
            child: QrImageView(
              data: _buildQRData(),
              version: QrVersions.auto,
              size: 180,
              backgroundColor: Colors.white,
              eyeStyle: const QrEyeStyle(
                eyeShape: QrEyeShape.square,
                color: Color(0xFF1A1A2E),
              ),
              dataModuleStyle: const QrDataModuleStyle(
                dataModuleShape: QrDataModuleShape.square,
                color: Color(0xFF1A1A2E),
              ),
            ),
          ),
          const SizedBox(height: 12),
          Text('Scan to view emergency information',
              style: AppTheme.bodySmall.copyWith(
                color: AppTheme.textMuted,
                fontSize: 12,
              )),
        ],
      ),
    );
  }

  Widget _buildShareButton() {
    return NeonButton(
      text: 'SHARE ICE CARD',
      icon: Icons.share_rounded,
      onPressed: _shareICECard,
      gradient: AppTheme.redGradient,
    );
  }
}
